version: '3'

services:
  mongo:
    container_name: clean_ts_mongo
    image: mongo:latest
    restart: always
    volumes:
      - ./docker:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-clean
    image: node:18
    working_dir: /home/glesio/.storage/clean-node-api
    restart: always
    command: bash -c "npm install --omit=dev && npm install nodemon -D && npm run debug"
    volumes:
      - ./dist/:/home/glesio/.storage/clean-node-api/dist/
      - ./package.json:/home/glesio/.storage/clean-node-api/package.json
    ports:
      - "3000:3000"
      - "9222:9222"
    links:
      - mongo
